#!/usr/bin/env python3
"""
AI-Based Alert Prioritization for Network Intrusion Detection Using Machine Learning

CSCI 5742 - Spring 2026 - Joseph Tesoriero & Tejal Jadhav

- This command-line tool displays IDS alerts that were already scored by the risk-layer notebook. 
- It is a lightweight demo program where users can choose the ranking method, number of alerts, and default or user-config results.

Examples:
    python alert_prioritization.py --rank risk --limit 20
    python alert_prioritization.py --rank severity --limit 10
    python alert_prioritization.py --rank probability --limit 10
    python alert_prioritization.py --rank fifo --limit 10
    python alert_prioritization.py --profile user-config --rank risk --limit 20
    python alert_prioritization.py --summary
    python alert_prioritization.py --metrics-table
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

try:
    import pandas as pd
except ImportError:
    print("[ERROR] pandas is required. Install it with: pip install pandas")
    sys.exit(1)


# File names generated by the risk-layer notebook
DEFAULT_ALERTS_CSV = "ranked_alerts_top_10000.csv"
DEFAULT_METRICS_CSV = "ranking_metrics.csv"
USER_CONFIG_ALERTS_CSV = "user_config_ranked_alerts_top_10000.csv"
USER_CONFIG_METRICS_CSV = "user_config_ranking_metrics.csv"


RISK_FORMULA = "RiskScore = P(Attack) * (Severity + AssetValue)"
HIGH_SEVERITY_THRESHOLD = 7


# Terminal colors for nicer demo output

RESET = "\033[0m"
BOLD = "\033[1m"
DIM = "\033[2m"
RED = "\033[91m"
ORANGE = "\033[93m"
YELLOW = "\033[33m"
GREEN = "\033[92m"
CYAN = "\033[96m"
WHITE = "\033[97m"

USE_COLOR = sys.stdout.isatty()


# Columns expected from the ranked alert CSV

REQUIRED_ALERT_COLUMNS = {
    "sample_index",
    "actual_label",
    "predicted_label",
    "predicted_class_probability",
    "p_benign",
    "p_malicious",
    "predicted_severity",
    "actual_severity",
    "asset_target",
    "asset_value",
    "risk_score",
    "actual_is_malicious",
    "actual_is_high_severity",
    "fifo_order",
}


# Columns expected from the metrics CSV
REQUIRED_METRIC_COLUMNS = {
    "method",
    "relevance_target",
    "k",
    "precision_at_k",
    "recall_at_k",
    "relevant_found",
    "total_relevant",
}


# Ranking options supported by the CLI
RANK_MAP = {
    "risk": ("risk_score", False, "Risk Score"),
    "severity": ("predicted_severity", False, "Severity Score"),
    "probability": ("p_malicious", False, "Malicious Probability"),
    "fifo": ("fifo_order", True, "FIFO Order"),
}


# Display labels for ranking methods
METHOD_LABELS = {
    "risk_score": "Risk Score",
    "probability_only": "Probability Only",
    "severity_only": "Severity Only",
    "fifo": "FIFO",
}


# Short asset names so the terminal table stays readable
ASSET_DISPLAY_NAMES = {
    "server_or_network_infrastructure": "server/net infra",
    "generic_or_unknown": "generic/unknown",
    "legacy_or_iot_device": "legacy/IoT",
    "web_server": "web server",
    "default": "default",
}

METHOD_ORDER = ["risk_score", "probability_only", "severity_only", "fifo"]

METRIC_METHOD_BY_RANK = {
    "risk": "risk_score",
    "probability": "probability_only",
    "severity": "severity_only",
    "fifo": "fifo",
}


# Add color to terminal text when colors are enabled.
def color(text, *codes):
    if not USE_COLOR:
        return str(text)
    return "".join(codes) + str(text) + RESET


# Shorten long text so table columns do not break.
def truncate(text: str, width: int) -> str:
    text = str(text)
    if len(text) <= width:
        return text
    if width <= 3:
        return text[:width]
    return text[: width - 3] + "..."


# Format one table cell with optional color.
def cell(text, width: int, align: str = "<", *codes) -> str:
    value = truncate(str(text), width)
    formatted = f"{value:{align}{width}}"
    return color(formatted, *codes) if codes else formatted


# Get the folder where this script is stored.
def script_dir() -> Path:
    return Path(__file__).resolve().parent


# Resolve relative file paths from the script folder.
def resolve_project_path(path: str | Path) -> Path:
    path = Path(path)
    if path.is_absolute():
        return path
    return script_dir() / path


# Print the tool title.
def print_banner() -> None:
    divider = color("  " + "=" * 78, CYAN)
    print()
    print(divider)
    print(color("  AI-Based Alert Prioritization for Network Intrusion Detection", BOLD, WHITE))
    print(color("  Risk-layer CLI demo for CICIoT2023 IDS alerts", BOLD, WHITE))
    print(color("  CSCI 5742 - Spring 2026 - Tesoriero & Jadhav", DIM))
    print(divider)
    print()


# Print the risk formula in simple terms.
def print_formula() -> None:
    print(color("  Risk Score Formula", BOLD))
    print(color(f"  {RISK_FORMULA}", CYAN, BOLD))
    print(color("    P(Attack)  = 1 - P(BENIGN), from ensemble model probabilities", DIM))
    print(color("    Severity   = predicted attack severity score", DIM))
    print(color("    AssetValue = synthetic asset importance score", DIM))
    print()


# Pick a color based on severity value.
def severity_color(severity: float) -> str:
    if severity >= 9:
        return RED
    if severity >= 7:
        return ORANGE
    if severity >= 5:
        return YELLOW
    return GREEN


# Pick a color based on final risk score.
def risk_color(risk_score: float) -> str:
    if risk_score >= 15:
        return RED
    if risk_score >= 10:
        return ORANGE
    if risk_score >= 5:
        return YELLOW
    return GREEN


# Convert risk score into a readable risk band.
def risk_label(risk_score: float) -> str:
    if risk_score >= 15:
        return "CRITICAL"
    if risk_score >= 10:
        return "HIGH"
    if risk_score >= 5:
        return "MEDIUM"
    return "LOW"


# Convert severity value into a readable severity band.
def severity_label(severity: float) -> str:
    if severity >= 9:
        return "CRITICAL"
    if severity >= 7:
        return "HIGH"
    if severity >= 5:
        return "MEDIUM"
    return "LOW"


# Convert long asset names into shorter display names.
def display_asset(asset_target: str) -> str:
    return ASSET_DISPLAY_NAMES.get(str(asset_target), str(asset_target))


# Show whether model prediction matches the actual label.
def prediction_status(predicted_label: str, actual_label: str) -> str:
    return "MATCH" if predicted_label == actual_label else "CHECK"


# Explain why an alert was ranked highly.
def score_reason(p_attack: float, severity: int, asset_value: int) -> str:
    return f"{p_attack:.1%} attack + sev {severity} + asset {asset_value}"


# Pick a color based on Precision@K.
def precision_color(precision: float) -> str:
    if precision >= 0.90:
        return GREEN
    if precision >= 0.70:
        return YELLOW
    return RED


# Load ranked alerts generated by the risk-layer notebook.
def load_alerts(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(
            f"Alert CSV not found: {path}\n"
            f"Run the risk-layer notebook first, or pass --input /path/to/file.csv."
        )

    df = pd.read_csv(path)
    missing = REQUIRED_ALERT_COLUMNS - set(df.columns)

    if missing:
        missing_list = ", ".join(sorted(missing))
        raise ValueError(f"Alert CSV is missing required columns: {missing_list}")

    return df


# Load Precision@K and Recall@K metrics.
def load_metrics(path: Path) -> pd.DataFrame | None:
    if not path.exists():
        print(color(f"  [!] Metrics file not found: {path}", ORANGE))
        return None

    df = pd.read_csv(path)
    missing = REQUIRED_METRIC_COLUMNS - set(df.columns)

    if missing:
        missing_list = ", ".join(sorted(missing))
        print(color(f"  [!] Metrics CSV missing columns: {missing_list}", ORANGE))
        return None

    return df


# Load optional user config JSON.
def load_config(config_path: Path) -> dict:
    if not config_path.exists():
        raise FileNotFoundError(f"Config file not found: {config_path}")

    with config_path.open("r", encoding="utf-8") as file:
        return json.load(file)


# Apply optional user severity settings from config.
def apply_severity_config(df: pd.DataFrame, config_path: Path) -> pd.DataFrame:
    """
    This only updates severity and risk score using the ranked CSV.
    It does not redo protocol-to-asset mapping because protocol columns are not
    available in the ranked alert CSV.
    """
    cfg = load_config(config_path)
    severity_map = cfg.get("severity_map", {})
    threshold = cfg.get("high_severity_threshold", HIGH_SEVERITY_THRESHOLD)

    if not severity_map:
        print(color(f"  [!] Config has no severity_map: {config_path}", ORANGE))
        return df

    df = df.copy()

    original_predicted = df["predicted_severity"].copy()
    original_actual = df["actual_severity"].copy()

    df["predicted_severity"] = df["predicted_label"].map(severity_map).fillna(original_predicted)
    df["actual_severity"] = df["actual_label"].map(severity_map).fillna(original_actual)

    df["predicted_severity"] = df["predicted_severity"].astype(int)
    df["actual_severity"] = df["actual_severity"].astype(int)

    # Same risk formula as the notebook.
    df["risk_score"] = df["p_malicious"] * (df["predicted_severity"] + df["asset_value"])

    # Recompute high-severity flags using the config threshold.
    df["actual_is_high_severity"] = df["actual_severity"] >= threshold
    df["predicted_is_high_severity"] = df["predicted_severity"] >= threshold

    print(color(f"  [OK] Applied severity config: {config_path.name}", GREEN))
    return df


# Mark predicted high-severity alerts using the notebook threshold.
def prepare_alerts(
    df: pd.DataFrame,
    high_severity_threshold: int = HIGH_SEVERITY_THRESHOLD,
) -> pd.DataFrame:
    df = df.copy()
    df["predicted_is_high_severity"] = df["predicted_severity"] >= high_severity_threshold
    return df


# Sort alerts using the selected ranking method.
def rank_alerts(df: pd.DataFrame, method: str) -> pd.DataFrame:
    column, ascending, _ = RANK_MAP[method]
    return df.sort_values(column, ascending=ascending).reset_index(drop=True)


# Print dataset-level summary.
def print_summary(df: pd.DataFrame) -> None:
    total = len(df)
    malicious = int(df["actual_is_malicious"].sum())
    predicted_high = int(df["predicted_is_high_severity"].sum())
    actual_high = int(df["actual_is_high_severity"].sum())

    divider = color("  " + "=" * 88, CYAN)
    small_divider = color("  " + "-" * 88, DIM)

    print(divider)
    print(color("  DATASET OVERVIEW", BOLD, WHITE))
    print(small_divider)
    print(f"  {'Total alerts loaded':<36} {total:>12,}")
    print(f"  {'Actually malicious alerts':<36} {malicious:>12,}  ({malicious / total * 100:.1f}%)")
    print(f"  {'Predicted high-severity alerts':<36} {predicted_high:>12,}  ({predicted_high / total * 100:.1f}%)")
    print(f"  {'Actually high-severity alerts':<36} {actual_high:>12,}  ({actual_high / total * 100:.1f}%)")
    print(divider)
    print()

    grouped = (
        df.groupby("predicted_label", as_index=False)
        .agg(
            number_of_alerts=("risk_score", "count"),
            avg_p_attack=("p_malicious", "mean"),
            max_severity=("predicted_severity", "max"),
            average_risk_score=("risk_score", "mean"),
            highest_risk_score=("risk_score", "max"),
        )
        .sort_values("highest_risk_score", ascending=False)
        .head(10)
    )

    print(divider)
    print(color("  TOP ATTACK TYPES BY HIGHEST RISK SCORE", BOLD, WHITE))
    print(small_divider)
    print(
        color(
            f"  {'Attack Type':<32} {'Alerts':>10} {'Avg P(Attack)':>15} "
            f"{'Max Sev':>9} {'Avg Risk':>10} {'Max Risk':>10}",
            DIM,
        )
    )
    print(small_divider)

    for row in grouped.itertuples(index=False):
        sev_code = severity_color(row.max_severity)
        risk_code = risk_color(row.highest_risk_score)

        print(
            f"  {color(row.predicted_label, sev_code):<32} "
            f"{row.number_of_alerts:>10,} "
            f"{row.avg_p_attack:>15.1%} "
            f"{color(row.max_severity, sev_code):>9} "
            f"{row.average_risk_score:>10.2f} "
            f"{color(f'{row.highest_risk_score:.2f}', risk_code):>10}"
        )

    print(divider)
    print_formula()


# Print important context from the risk-layer notebook.
def print_notebook_context(
    df: pd.DataFrame,
    metrics_df: pd.DataFrame | None,
    rank_method: str,
) -> None:
    total = len(df)
    malicious = int(df["actual_is_malicious"].sum())
    predicted_high = int(df["predicted_is_high_severity"].sum())
    matches = int((df["predicted_label"] == df["actual_label"]).sum())
    unique_attacks = int(df["predicted_label"].nunique())
    critical_risk = int((df["risk_score"] >= 15).sum())
    max_risk = float(df["risk_score"].max()) if total else 0.0
    avg_risk = float(df["risk_score"].mean()) if total else 0.0

    metric_method = METRIC_METHOD_BY_RANK[rank_method]

    divider = color("  " + "─" * 78, CYAN)
    small_divider = color("  " + "─" * 78, DIM)

    print(divider)
    print(color("  RISK-LAYER NOTEBOOK CONTEXT", BOLD, WHITE))
    print(small_divider)
    print(color("  Source: precomputed CSV outputs from risk_layer.ipynb", DIM))
    print(color(f"  Formula: {RISK_FORMULA}", CYAN, BOLD))
    print(color("  P(Attack) is implemented as P(malicious) = 1 - P(BENIGN).", DIM))
    print()
    print(f"  {'Alerts in current selection':<34} {total:>12,}")
    print(f"  {'Actually malicious alerts':<34} {malicious:>12,}  ({malicious / total * 100:.1f}%)")
    print(f"  {'Predicted high-severity alerts':<34} {predicted_high:>12,}  ({predicted_high / total * 100:.1f}%)")
    print(f"  {'Critical-risk alerts':<34} {critical_risk:>12,}  ({critical_risk / total * 100:.1f}%)")
    print(f"  {'Unique predicted attack types':<34} {unique_attacks:>12,}")
    print(f"  {'Prediction matches actual label':<34} {matches:>12,}  ({matches / total * 100:.1f}%)")
    print(f"  {'Average risk score':<34} {avg_risk:>12.2f}")
    print(f"  {'Highest risk score':<34} {color(f'{max_risk:>12.2f}', risk_color(max_risk))}")

    if metrics_df is not None:
        snapshot = metrics_df[
            (metrics_df["method"] == metric_method)
            & (metrics_df["relevance_target"] == "actual_is_malicious")
            & (metrics_df["k"].isin([100, 1000, 10000]))
        ].sort_values("k")

        if not snapshot.empty:
            print()
            print(color(f"  Precision@K snapshot for selected ranking: {METHOD_LABELS[metric_method]}", BOLD))

            for row in snapshot.itertuples(index=False):
                precision = color(f"{row.precision_at_k:.1%}", precision_color(row.precision_at_k))

                print(
                    f"  K={int(row.k):<6} "
                    f"Precision={precision:<16} "
                    f"Recall={row.recall_at_k:.4%} "
                    f"Relevant found={int(row.relevant_found):,}"
                )

    print("\n" + divider)


# Print Precision@K and Recall@K metrics.
def print_metrics(metrics_df: pd.DataFrame | None) -> None:
    if metrics_df is None:
        print(color("  [!] No metrics table available.", ORANGE))
        return

    divider = color("  " + "─" * 78, CYAN)
    small_divider = color("  " + "─" * 78, DIM)

    for target, target_label in [
        ("actual_is_malicious", "ALL MALICIOUS ALERTS"),
        ("actual_is_high_severity", "HIGH-SEVERITY ALERTS"),
    ]:
        subset = metrics_df[metrics_df["relevance_target"] == target]

        if subset.empty:
            continue

        k_values = sorted(subset["k"].unique())

        print(divider)
        print(color("  HIGH-SEVERITY ALERT EVALUATION", BOLD, CYAN))
        print(color("  Precision@K and Recall@K", DIM))
        print(color("  Precision@K answers: if we review the top K alerts, how many are relevant?", DIM))
        print(small_divider)

        k_header = " ".join(f"{('K=' + str(k)):>8}" for k in k_values)

        print(color(f"{'Method':<18} {'Metric':<12} {k_header}", DIM))
        print(small_divider)

        for method in METHOD_ORDER:
            method_data = subset[subset["method"] == method].sort_values("k")

            if method_data.empty:
                continue

            method_label = METHOD_LABELS.get(method, method)

            precision_row = ""
            recall_row = ""

            for _, row in method_data.iterrows():
                p = f"{row['precision_at_k']:.1%}".rjust(8)
                r = f"{row['recall_at_k']:.4%}".rjust(8)

                precision_row += color(p, precision_color(row["precision_at_k"])) + " "
                recall_row += color(r, DIM) + " "

            print(
                print(''),
                f"  {color(method_label, BOLD):<22}"
                f"{'Precision@K':<14}"
                f"{precision_row}"
            )

            print(
                f"  {'':<22}"
                f"{'Recall@K':<14}"
                f"{recall_row}"
            )

            print()


# Print top alerts as a readable terminal table.
def print_alerts(df: pd.DataFrame, limit: int, rank_method: str) -> None:
    ranked = rank_alerts(df, rank_method)
    top = ranked.head(limit)

    _, _, method_display = RANK_MAP[rank_method]

    divider = color("  " + "=" * 146, CYAN)
    small_divider = color("  " + "-" * 146, DIM)

    mismatch_count = int((top["predicted_label"] != top["actual_label"]).sum())

    top_attack_mix = ", ".join(
        f"{label} ({count})"
        for label, count in top["predicted_label"].value_counts().head(3).items()
    )

    top_asset_mix = ", ".join(
        f"{display_asset(label)} ({count})"
        for label, count in top["asset_target"].value_counts().head(3).items()
    )

    print(divider)
    print(color(f"  TOP {len(top)} ALERTS", BOLD, WHITE) + color(f"  -  Ranked by: {method_display}", DIM))
    print(color(f"  Top attack mix: {top_attack_mix}", DIM))
    print(color(f"  Top asset mix:  {top_asset_mix}", DIM))
    print(color(f"  Model checks:   {mismatch_count} of top {len(top)} predicted labels differ from actual labels", DIM))
    print(small_divider)

    print(
        color(
            f"  {'#':<3} {'Sample':>8} {'Predicted Label':<24} {'Actual Label':<24} "
            f"{'Status':<7} {'P(Attack)':>9} {'Sev':>3} {'Asset':<19} "
            f"{'AVal':>4} {'Risk':>6} {'Band':<8} {'Why Ranked High':<33}",
            DIM,
        )
    )

    print(small_divider)

    for priority, row in enumerate(top.itertuples(index=False), start=1):
        predicted = str(row.predicted_label)
        actual = str(row.actual_label)
        severity = int(row.predicted_severity)
        risk = float(row.risk_score)
        p_attack = float(row.p_malicious)
        asset_class = display_asset(row.asset_target)
        asset_value = int(row.asset_value)
        sample_index = int(row.sample_index)

        status = prediction_status(predicted, actual)
        status_code = GREEN if status == "MATCH" else YELLOW

        risk_band = risk_label(risk)
        sev_code = severity_color(severity)
        risk_code = risk_color(risk)
        actual_code = YELLOW if predicted != actual else DIM

        print(
            "  "
            f"{cell(priority, 3, '>', DIM)} "
            f"{cell(sample_index, 8, '>')} "
            f"{cell(predicted, 24, '<', sev_code)} "
            f"{cell(actual, 24, '<', actual_code)} "
            f"{cell(status, 7, '<', status_code)} "
            f"{cell(f'{p_attack:.1%}', 9, '>')} "
            f"{cell(severity, 3, '>', sev_code)} "
            f"{cell(asset_class, 19, '<', DIM)} "
            f"{cell(asset_value, 4, '>', DIM)} "
            f"{cell(f'{risk:.2f}', 6, '>', risk_code)} "
            f"{cell(risk_band, 8, '<', risk_code)} "
            f"{cell(score_reason(p_attack, severity, asset_value), 33, '<', DIM)}"
        )

    print(small_divider)

    print(
        "  "
        + color("Severity: ", BOLD)
        + color("9-10 critical", RED)
        + " | "
        + color("7-8 high", ORANGE)
        + " | "
        + color("5-6 medium", YELLOW)
        + " | "
        + color("<5 low", GREEN)
        + " | "
        + color("CHECK = predicted label differs from actual label", YELLOW)
    )

    print(
        "  "
        + color("Asset value: ", BOLD)
        + color("9 critical asset", RED)
        + " | "
        + color("7 important asset", ORANGE)
        + " | "
        + color("5 medium asset", YELLOW)
        + " | "
        + color("3 or lower low/context asset", GREEN)
    )

    print(divider)
    print()


# Define command-line flags.
def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Display and compare precomputed CICIoT2023 IDS alert rankings."
    )

    parser.add_argument(
        "--profile",
        choices=["default", "user-config"],
        default="default",
        help=(
            "Which precomputed result files to use. "
            "default uses ranked_alerts_top_10000.csv/ranking_metrics.csv; "
            "user-config uses user_config_ranked_alerts_top_10000.csv/user_config_ranking_metrics.csv."
        ),
    )

    parser.add_argument("--input", default=None, help="Optional custom ranked-alert CSV path.")
    parser.add_argument("--metrics", default=None, help="Optional custom ranking-metrics CSV path.")
    parser.add_argument("--limit", type=int, default=10, help="Number of alerts to display.")

    parser.add_argument(
        "--rank",
        choices=["risk", "severity", "probability", "fifo"],
        default="risk",
        help="Ranking method to display.",
    )

    parser.add_argument(
        "--filter",
        default=None,
        help="Filter to a predicted attack type, for example MITM-ARPSPOOFING.",
    )

    parser.add_argument(
        "--high-only",
        action="store_true",
        help="Show only alerts whose predicted severity is high.",
    )

    parser.add_argument(
        "--config",
        default=None,
        help="Optional config JSON for severity-only demo overrides.",
    )

    parser.add_argument("--summary", action="store_true", help="Show dataset and attack-type summary.")
    parser.add_argument("--metrics-table", action="store_true", help="Show Precision@K and Recall@K table.")
    parser.add_argument("--no-color", action="store_true", help="Disable terminal colors.")

    return parser


# Choose default or user-config CSV files.
def choose_default_files(args: argparse.Namespace) -> tuple[Path, Path]:
    if args.profile == "user-config":
        alerts_path = USER_CONFIG_ALERTS_CSV
        metrics_path = USER_CONFIG_METRICS_CSV
    else:
        alerts_path = DEFAULT_ALERTS_CSV
        metrics_path = DEFAULT_METRICS_CSV

    if args.input is not None:
        alerts_path = args.input

    if args.metrics is not None:
        metrics_path = args.metrics

    return resolve_project_path(alerts_path), resolve_project_path(metrics_path)


def main() -> None:
    global USE_COLOR

    args = build_parser().parse_args()

    if args.no_color:
        USE_COLOR = False

    if args.limit < 1:
        raise ValueError("--limit must be at least 1.")

    alerts_path, metrics_path = choose_default_files(args)

    print_banner()
    print(color(f"  Result profile: {args.profile}", BOLD))
    print(color(f"  Alerts CSV: {alerts_path}", DIM))
    print(color(f"  Metrics CSV: {metrics_path}", DIM))
    print()

    alerts = load_alerts(alerts_path)
    alerts = prepare_alerts(alerts)

    if args.config:
        alerts = apply_severity_config(alerts, resolve_project_path(args.config))

    if args.filter:
        attack_type = args.filter.strip().upper()
        alerts = alerts[alerts["predicted_label"].str.upper() == attack_type]

        if alerts.empty:
            print(color(f"  [!] No alerts matched predicted attack type: {attack_type}", ORANGE))
            return

        print(color(f"  [OK] Filtered to {attack_type}: {len(alerts):,} alerts", GREEN))
        print()

    if args.high_only:
        alerts = alerts[alerts["predicted_is_high_severity"]]

        if alerts.empty:
            print(color("  [!] No predicted high-severity alerts in this selection.", ORANGE))
            return

        print(color(f"  [OK] Predicted high-severity only: {len(alerts):,} alerts", GREEN))
        print()

    if args.summary:
        print_summary(alerts)
        return

    if args.metrics_table:
        print_metrics(load_metrics(metrics_path))
        return

    metrics_df = load_metrics(metrics_path)

    print_notebook_context(alerts, metrics_df, args.rank)
    print_alerts(alerts, args.limit, args.rank)


if __name__ == "__main__":
    main()
